#!/usr/bin/env python3
"""
Generate systemd service+timer units from registry.json.

Phase 3 of the fleet review. The orchestrator's in-process `schedule` loop has
no persistence: it fires jobs whose time arrives while the process is running,
and a slot missed during a reboot is gone with nothing recording that it was
owed. This machine reboots often for the root-disk work, and the job most
exposed to that is the one alert with a deadline attached.

systemd timers fix exactly that with Persistent=true, and bring per-job
journald logs, real `systemctl status`, and isolation - one hung job can no
longer stall the others the way it can inside a single-threaded loop.

Units are GENERATED, never hand-edited: the registry stays the one place a job
is described, so the schedule and the monitoring cannot drift apart.

  ops/gen_units.py            write units to ./ops/units/ and diff against live
  ops/gen_units.py --install  write, install to /etc/systemd/system, reload

Exit code contract is preserved end to end: 4 (degraded) is deliberately NOT
listed in SuccessExitStatus, so a report that went out incomplete still trips
OnFailure and still pages - it is just worded differently by the handler.
"""
import json, os, subprocess, sys, filecmp

REGISTRY  = "/home/work/fraqtoos/registry.json"
OUT_DIR   = "/home/work/fraqtoos/ops/units"
SYSTEMD   = "/etc/systemd/system"

SERVICE = """# GENERATED by fraqtoos/ops/gen_units.py from registry.json — do not hand-edit.
# Change the registry entry and regenerate, or the schedule and the monitoring
# will drift apart, which is the problem this whole layer exists to remove.
[Unit]
Description={description}
After=network-online.target
Wants=network-online.target
OnFailure=fraqtoos-alert@%n.service

[Service]
Type=oneshot
User=work
WorkingDirectory={cwd}
Environment=DISPLAY=:0
# Exit 4 means "sent, but a source was missing". Left OUT of SuccessExitStatus
# on purpose: an incomplete report must still reach OnFailure and still page.
ExecStart={exec}
TimeoutStartSec={timeout_sec}
"""

TIMER = """# GENERATED by fraqtoos/ops/gen_units.py from registry.json — do not hand-edit.
[Unit]
Description={description} (timer)

[Timer]
{on_calendar}
# The whole reason for this migration: if the machine was down or rebooting at
# the scheduled minute, run as soon as it is back rather than skipping the day.
Persistent=true
AccuracySec=30s
Unit={stem}.service

[Install]
WantedBy=timers.target
"""


def jobs_with_units() -> list:
    with open(REGISTRY) as f:
        return [j for j in json.load(f)["jobs"] if j.get("systemd")]


def render(job: dict) -> dict:
    sd   = job["systemd"]
    stem = job["unit"].rsplit(".", 1)[0]
    # on_calendar may be one expression or several; systemd accepts repeated
    # OnCalendar= lines and fires on each, which is how a job gets two slots a
    # day without two units.
    cal = sd["on_calendar"]
    cal_lines = "\n".join(f"OnCalendar={c}" for c in
                           (cal if isinstance(cal, list) else [cal]))
    ctx  = {"description": sd["description"], "cwd": sd["cwd"], "exec": sd["exec"],
            "timeout_sec": sd.get("timeout_sec", 300),
            "on_calendar": cal_lines, "stem": stem}
    return {f"{stem}.service": SERVICE.format(**ctx),
            f"{stem}.timer":   TIMER.format(**ctx)}


def main() -> int:
    install = "--install" in sys.argv
    os.makedirs(OUT_DIR, exist_ok=True)

    written, changed = [], []
    for job in jobs_with_units():
        for name, text in render(job).items():
            path = os.path.join(OUT_DIR, name)
            with open(path, "w") as f:
                f.write(text)
            written.append(name)
            live = os.path.join(SYSTEMD, name)
            if not os.path.exists(live) or not filecmp.cmp(path, live, shallow=False):
                changed.append(name)

    print(f"rendered {len(written)} unit file(s) into {OUT_DIR}")
    for n in written:
        print(f"  {'CHANGED' if n in changed else 'in sync'}  {n}")

    if not install:
        if changed:
            print(f"\n{len(changed)} unit(s) differ from {SYSTEMD}. Re-run with --install.")
        return 0

    if not changed:
        print("\nnothing to install.")
        return 0

    for n in changed:
        subprocess.run(["sudo", "-n", "cp", os.path.join(OUT_DIR, n),
                        os.path.join(SYSTEMD, n)], check=True)
    subprocess.run(["sudo", "-n", "systemctl", "daemon-reload"], check=True)
    print(f"\ninstalled {len(changed)} unit(s) and reloaded systemd.")
    print("enable timers with:  sudo systemctl enable --now <name>.timer")
    return 0


if __name__ == "__main__":
    sys.exit(main())
